services:
  mongodb:
    image: mongo:latest
    container_name: hypesoft_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.7
    container_name: hypesoft_auth
    command: start-dev --import-realm
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HOSTNAME_STRICT: "false"
      KC_HTTP_ENABLED: "true"
      KC_HEALTH_ENABLED: "true"
      KC_PROXY_HEADERS: "xforwarded"
      KC_DB: "dev-file"
      JAVA_OPTS_APPEND: "-Xms256m -Xmx768m"
    ports:
      - "8080:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./keycloak/import:/opt/keycloak/data/import
    healthcheck:
      # healthcheck simples (sem grep) e mais tolerante
      test: ["CMD-SHELL", "wget -qO- http://localhost:8080/health/ready >/dev/null 2>&1 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 120
      start_period: 120s
    cpus: 1.5
    mem_limit: 1024m

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hypesoft_api
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__MongoDb=mongodb://mongodb:27017/HypesoftDb
    depends_on:
      mongodb:
        condition: service_started
      keycloak:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: hypesoft_web
    ports:
      - "5173:80"
    depends_on:
      backend:
        condition: service_started

volumes:
  mongo_data:
  keycloak_data: