services:
  mongodb:
    image: mongo:latest
    container_name: hypesoft_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: hypesoft_mongo_express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH: "false"
    depends_on:
      - mongodb

# Essa parte foi a mais dificil de configurar, tive que ler a documentação do Keycloak e testar várias opções de configuração para conseguir fazer ele funcionar corretamente com o backend. O mais importante foi configurar as variáveis de 
# ambiente para criar o usuário admin e permitir o acesso via HTTP, além de montar os volumes para persistir os dados e importar o realm.
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: hypesoft_auth
    command: start-dev --import-realm
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HOSTNAME_STRICT: "false"
      KC_HTTP_ENABLED: "true"
      KC_HEALTH_ENABLED: "true"
      KC_PROXY_HEADERS: "xforwarded"
      KC_DB: "dev-file"
      JAVA_OPTS_APPEND: "-Xms256m -Xmx768m"
    ports:
      - "8080:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./keycloak/import:/opt/keycloak/data/import

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hypesoft_api
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__MongoDb=mongodb://mongodb:27017/HypesoftDb
    depends_on:
      - mongodb
      - keycloak

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: hypesoft_web
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongo_data:
  keycloak_data: