version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: hypesoft_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: hypesoft_auth
    command: start-dev
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HOSTNAME_STRICT: "false"
      KC_HTTP_ENABLED: "true"
    ports:
      - "8080:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hypesoft_api
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__MongoDb=mongodb://mongodb:27017/HypesoftDb
    depends_on:
      - mongodb
      - keycloak

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: hypesoft_web
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  mongo_data:
  keycloak_data: